### ISSUE TITLE
이용 동의 약관 / 개인정보 수집, 동의

### ISSUE THREAD

**Issue by jeongah2651** [imaginer-dev/DateLeaf#16]
이용 동의 약관 , 개인정보 수집 동의 

- 회원가입시 위 동의 사항을 받음. (관련된 페이지 제작 필요)

**Comment by Rose4tune** [comment]
interface 타입을 any[] 지정 시 다음과 같은 에러 발생
`error  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any`

해결법
```
//.eslintrc.json
{
    ...
    "rules": {
        // Unexpected any. Specify a different type 문구 제거
        "@typescript-eslint/no-explicit-any": "off", 
        // React, { ReactElement } from "react" 설정 안함
        "@typescript-eslint/explicit-module-boundary-types": "off",
    }
}
```

참고 링크 : https://velog.io/@j_wisdom_h/Unexpected-any.-Specify-a-different-type.-eslint
