### ISSUE TITLE
그룹 일정 추가시 초대 가능한 회원리스트를 확인할 수 있어야 한다.

### ISSUE THREAD

**Issue by CreatorDodo** [imaginer-dev/DateLeaf#49]

**Comment by jane1107** [comment]
[ 회원 리스트 검색 검토 ]
-> 현재 unique key 값이 이메일 밖에 없어서 이메일로 친구를 초대해야 함.
-> 이메일로 검색하는 것보다 닉네임으로 검색하는 게 더 편할 것 같아서, 닉네임 필드 추가 필요.

**Comment by jane1107** [comment]
프로파일 db 에 email 이 없기 때문에 어차피 email 로 친구 검색 안됨

**Comment by jane1107** [comment]
닉네임 말고 profile 에 user_name 으로 검색!!!!
